version: '3'
services:
  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: douyin
    ports:
    - "3306:3306"
  redis:
    image: redis:7.0.0
    ports:
      - "6379:6379"

